spring:
  application:
    name: cpe_java_mod03_s03_tienda

  # Database configuration
  datasource:
    url: jdbc:mariadb://localhost:3306/tienda
    username: root
    password: root

  security:
    user:
      name: user01
      password: 123456